site_name: Assimilating Radar Observations using WRF-DART Cycling

theme:
  name: readthedocs

docs_dir: docs

nav:
  - Introduction: intro.md
  - Building Models: building_models.md
  - Experiment Setup: experiment_setup.md
  - Data Download: data_download.md
  - Generating ICBC and Initial Forecast: icbc_ensemble_forecast.md
